### ISSUE TITLE
Why is it visible when scanning through walls?

### ISSUE THREAD

**Issue by Paradox75831004** [Kaszana102/Roller-enemy#4]
![image](https://github.com/user-attachments/assets/5b751a52-492b-487c-86fd-efc84b42551f)
![image](https://github.com/user-attachments/assets/9d58b2ce-d5b2-44c3-86fe-ef568ea530ec)

**Comment by Paradox75831004** [comment]
01933057-968f-16c6-b8f9-9f68681fd687

**Comment by Paradox75831004** [comment]
![image](https://github.com/user-attachments/assets/30bafb4c-a87f-4616-b8ff-a4619a7543f2)
Perhaps he has some influence on this, but it is unlikely

**Comment by Kaszana102** [comment]
oh, i see! It seems one checkbox wasn't ticked!
![image](https://github.com/user-attachments/assets/6c6fd816-bd52-4bb9-bb9f-31748bde2a3b)

Updated on thunderstore. It should work now.
